services:
  - type: web
    name: Elevenyts
    runtime: python
    buildCommand: pip install -U -r requirements.txt
    startCommand: bash -c "python web.py & exec python -m Elevenyts"
    healthCheckPath: /health
    plan: free
